vich_uploader:
  db_driver: orm

  mappings:
    product_image:
      uri_prefix: /~19_moryc/licencjat/uploads
      upload_destination: '%kernel.project_dir%/public/uploads'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer